### ISSUE TITLE
Unescaped left brace in regex is illegal here in regex

### ISSUE THREAD

**Issue by eserte** [vti/protocol-socketio#1] opened 2016-08-21 18:32 UTC
t/message.t fails with bleadperl (5.25.x):

```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^5:1::{ <-- HERE .*}$/ at t/message.t line 54.
# Looks like your test exited with 255 before it could output anything.
t/message.t .... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 31/31 subtests 
```

**Comment by jkeenan** [comment] 2017-01-09 14:10
This is a bug report for:

Protocol-SocketIO-0.06

Due to unescaped left braces in some regular expression patterns in your code, your module won't work on 5.26.0. The CPAN Tester automated testing service cannot test your distribution on new versions of Perl until it is fixed and any modules that depend on yours will not work either.  Please see:

http://matrix.cpantesters.org/?dist=Protocol-SocketIO

Here is a link to all modules that depend on yours:

http://deps.cpantesters.org/depended-on-by.pl?dist=Protocol-SocketIO

We would appreciate help in sorting this out before the new version of Perl is released in May of this year. These errors are quite easy to correct and I would be happy to lend a hand.

I'm including a log file of my failure to build and install using "cpanm".

Thanks!

Jim Keenan
[protocol-socketio.log.pdf](https://github.com/vti/protocol-socketio/files/693645/protocol-socketio.log.pdf)

**Comment by vti** [comment] 2017-01-09 15:19
Fixed.

**Closed as completed by vti** 2017-01-09 15:19 UTC

**Comment by jkeenan** [comment] 2017-01-09 16:09
Confirmed.
```
Building and testing Protocol-SocketIO-0.07
cp lib/Protocol/SocketIO/Path.pm blib/lib/Protocol/SocketIO/Path.pm
cp lib/Protocol/SocketIO/Message.pm blib/lib/Protocol/SocketIO/Message.pm
cp lib/Protocol/SocketIO/Handshake.pm blib/lib/Protocol/SocketIO/Handshake.pm
cp lib/Protocol/SocketIO.pm blib/lib/Protocol/SocketIO.pm
t/handshake.t .. ok
t/message.t .... ok
t/path.t ....... ok
All tests successful.
Files=3, Tests=42,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.11 cusr  0.01 csys =  0.16 CPU)
Result: PASS
Installing /home/jkeenan/testing/blead/lib/perl5/site_perl/5.25.9/Protocol/SocketIO.pm
Installing /home/jkeenan/testing/blead/lib/perl5/site_perl/5.25.9/Protocol/SocketIO/Handshake.pm
Installing /home/jkeenan/testing/blead/lib/perl5/site_perl/5.25.9/Protocol/SocketIO/Path.pm
Installing /home/jkeenan/testing/blead/lib/perl5/site_perl/5.25.9/Protocol/SocketIO/Message.pm
-> OK
Successfully installed Protocol-SocketIO-0.07
```
Thanks for your rapid response.
Jim Keenan
